# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rodrigo0345/Work/graphics-learning

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rodrigo0345/Work/graphics-learning

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rodrigo0345/Work/graphics-learning/CMakeFiles /home/rodrigo0345/Work/graphics-learning//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rodrigo0345/Work/graphics-learning/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rendering_engine

# Build rule for target.
rendering_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rendering_engine
.PHONY : rendering_engine

# fast build rule for target.
rendering_engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rendering_engine.dir/build.make CMakeFiles/rendering_engine.dir/build
.PHONY : rendering_engine/fast

#=============================================================================
# Target rules for targets named build

# Build rule for target.
build: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build
.PHONY : build

# fast build rule for target.
build/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.dir/build.make CMakeFiles/build.dir/build
.PHONY : build/fast

#=============================================================================
# Target rules for targets named debug

# Build rule for target.
debug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 debug
.PHONY : debug

# fast build rule for target.
debug/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/build
.PHONY : debug/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

src/array.o: src/array.c.o
.PHONY : src/array.o

# target to build an object file
src/array.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rendering_engine.dir/build.make CMakeFiles/rendering_engine.dir/src/array.c.o
.PHONY : src/array.c.o

src/array.i: src/array.c.i
.PHONY : src/array.i

# target to preprocess a source file
src/array.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rendering_engine.dir/build.make CMakeFiles/rendering_engine.dir/src/array.c.i
.PHONY : src/array.c.i

src/array.s: src/array.c.s
.PHONY : src/array.s

# target to generate assembly for a file
src/array.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rendering_engine.dir/build.make CMakeFiles/rendering_engine.dir/src/array.c.s
.PHONY : src/array.c.s

src/display.o: src/display.c.o
.PHONY : src/display.o

# target to build an object file
src/display.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rendering_engine.dir/build.make CMakeFiles/rendering_engine.dir/src/display.c.o
.PHONY : src/display.c.o

src/display.i: src/display.c.i
.PHONY : src/display.i

# target to preprocess a source file
src/display.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rendering_engine.dir/build.make CMakeFiles/rendering_engine.dir/src/display.c.i
.PHONY : src/display.c.i

src/display.s: src/display.c.s
.PHONY : src/display.s

# target to generate assembly for a file
src/display.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rendering_engine.dir/build.make CMakeFiles/rendering_engine.dir/src/display.c.s
.PHONY : src/display.c.s

src/light.o: src/light.c.o
.PHONY : src/light.o

# target to build an object file
src/light.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rendering_engine.dir/build.make CMakeFiles/rendering_engine.dir/src/light.c.o
.PHONY : src/light.c.o

src/light.i: src/light.c.i
.PHONY : src/light.i

# target to preprocess a source file
src/light.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rendering_engine.dir/build.make CMakeFiles/rendering_engine.dir/src/light.c.i
.PHONY : src/light.c.i

src/light.s: src/light.c.s
.PHONY : src/light.s

# target to generate assembly for a file
src/light.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rendering_engine.dir/build.make CMakeFiles/rendering_engine.dir/src/light.c.s
.PHONY : src/light.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rendering_engine.dir/build.make CMakeFiles/rendering_engine.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rendering_engine.dir/build.make CMakeFiles/rendering_engine.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rendering_engine.dir/build.make CMakeFiles/rendering_engine.dir/src/main.c.s
.PHONY : src/main.c.s

src/matrix.o: src/matrix.c.o
.PHONY : src/matrix.o

# target to build an object file
src/matrix.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rendering_engine.dir/build.make CMakeFiles/rendering_engine.dir/src/matrix.c.o
.PHONY : src/matrix.c.o

src/matrix.i: src/matrix.c.i
.PHONY : src/matrix.i

# target to preprocess a source file
src/matrix.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rendering_engine.dir/build.make CMakeFiles/rendering_engine.dir/src/matrix.c.i
.PHONY : src/matrix.c.i

src/matrix.s: src/matrix.c.s
.PHONY : src/matrix.s

# target to generate assembly for a file
src/matrix.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rendering_engine.dir/build.make CMakeFiles/rendering_engine.dir/src/matrix.c.s
.PHONY : src/matrix.c.s

src/mesh.o: src/mesh.c.o
.PHONY : src/mesh.o

# target to build an object file
src/mesh.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rendering_engine.dir/build.make CMakeFiles/rendering_engine.dir/src/mesh.c.o
.PHONY : src/mesh.c.o

src/mesh.i: src/mesh.c.i
.PHONY : src/mesh.i

# target to preprocess a source file
src/mesh.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rendering_engine.dir/build.make CMakeFiles/rendering_engine.dir/src/mesh.c.i
.PHONY : src/mesh.c.i

src/mesh.s: src/mesh.c.s
.PHONY : src/mesh.s

# target to generate assembly for a file
src/mesh.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rendering_engine.dir/build.make CMakeFiles/rendering_engine.dir/src/mesh.c.s
.PHONY : src/mesh.c.s

src/triangle.o: src/triangle.c.o
.PHONY : src/triangle.o

# target to build an object file
src/triangle.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rendering_engine.dir/build.make CMakeFiles/rendering_engine.dir/src/triangle.c.o
.PHONY : src/triangle.c.o

src/triangle.i: src/triangle.c.i
.PHONY : src/triangle.i

# target to preprocess a source file
src/triangle.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rendering_engine.dir/build.make CMakeFiles/rendering_engine.dir/src/triangle.c.i
.PHONY : src/triangle.c.i

src/triangle.s: src/triangle.c.s
.PHONY : src/triangle.s

# target to generate assembly for a file
src/triangle.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rendering_engine.dir/build.make CMakeFiles/rendering_engine.dir/src/triangle.c.s
.PHONY : src/triangle.c.s

src/vector.o: src/vector.c.o
.PHONY : src/vector.o

# target to build an object file
src/vector.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rendering_engine.dir/build.make CMakeFiles/rendering_engine.dir/src/vector.c.o
.PHONY : src/vector.c.o

src/vector.i: src/vector.c.i
.PHONY : src/vector.i

# target to preprocess a source file
src/vector.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rendering_engine.dir/build.make CMakeFiles/rendering_engine.dir/src/vector.c.i
.PHONY : src/vector.c.i

src/vector.s: src/vector.c.s
.PHONY : src/vector.s

# target to generate assembly for a file
src/vector.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rendering_engine.dir/build.make CMakeFiles/rendering_engine.dir/src/vector.c.s
.PHONY : src/vector.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... build"
	@echo "... debug"
	@echo "... run"
	@echo "... rendering_engine"
	@echo "... src/array.o"
	@echo "... src/array.i"
	@echo "... src/array.s"
	@echo "... src/display.o"
	@echo "... src/display.i"
	@echo "... src/display.s"
	@echo "... src/light.o"
	@echo "... src/light.i"
	@echo "... src/light.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/matrix.o"
	@echo "... src/matrix.i"
	@echo "... src/matrix.s"
	@echo "... src/mesh.o"
	@echo "... src/mesh.i"
	@echo "... src/mesh.s"
	@echo "... src/triangle.o"
	@echo "... src/triangle.i"
	@echo "... src/triangle.s"
	@echo "... src/vector.o"
	@echo "... src/vector.i"
	@echo "... src/vector.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

